language: python
dist: bionic
sudo: required

addons:
  apt:
    update: true

stages:
  - pipeline

install:
  - pip install --user -r requirements.txt

jobs:
  include:
    - stage: pipeline
      name: "Pipeline process"
      script: "python src/pipeline/main.py"
