language: python
dist: bionic
sudo: required

addons:
  apt:
    update: true

branches:
  except:
    - master

python:
  - "3.7"

stages:
  - pipeline

install:
  - pip install -r requirements.txt
  - pip install dist/mcsdk-automation-framework-core-1.0.0.tar.gz

jobs:
  include:
    - stage: pipeline
      name: "Pipeline process"
      script: "python src/pipeline/main.py"
