language: python
dist: bionic
sudo: required

addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-dev
      - python3-setuptools

branches:
  except:
    - master

python:
  - "3.7"

stages:
  - pipeline

before_install:
  - pip3 install wheel --no-cache-dir

install:
  - pip3 install -r requirements.txt
  - python3 setup.py sdist
  - pip3 install dist/mcsdk-automation-framework-core-0.0.0.tar.gz

jobs:
  include:
    - stage: pipeline
      name: "Pipeline process"
      script: python3 src/pipeline/main.py
